# Generated by Django 5.1.7 on 2025-04-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="previous_password_hash",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Hash da senha anterior",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="Equipe"),
        ),
    ]
