# Generated by Django 5.1.7 on 2025-03-29 00:56

import django.db.models.deletion
import transactions.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0003_alter_bank_id_alter_category_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Data de pagamento")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LATE", "Atrasado"),
                            ("PENDING", "Em Aberto"),
                            ("PAID", "Pago"),
                            ("OVERDUE", "Vencido"),
                            ("RECEIVED", "Recebido"),
                        ],
                        default="PENDING",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.bank",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"type": "EXPENSE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.category",
                        validators=[transactions.validators.validate_expense_category],
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.paymentmethod",
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Data de pagamento")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LATE", "Atrasado"),
                            ("PENDING", "Em Aberto"),
                            ("PAID", "Pago"),
                            ("OVERDUE", "Vencido"),
                            ("RECEIVED", "Recebido"),
                        ],
                        default="PENDING",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.bank",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"type": "REVENUE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.category",
                        validators=[transactions.validators.validate_revenue_category],
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "ordering": ["-payment_date"],
            },
        ),
    ]
