# Generated by Django 5.1.7 on 2025-03-29 05:16

import django.db.models.deletion
import transactions.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="common.bank",
                verbose_name="Banco",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"type": "REVENUE"},
                on_delete=django.db.models.deletion.PROTECT,
                to="common.category",
                validators=[transactions.validators.validate_revenue_category],
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
