name: CI PulseVault

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        
    - name: Run Django Tests
      env:
        DJANGO_SECRET_KEY: testing_key
        DEBUG: True
        ALLOWED_HOSTS: localhost,127.0.0.1
        DOCKER_MODE: False
      run: |
        python manage.py test
        
    - name: Run Flake8
      run: flake8 .

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker compose version
    
    - name: Docker Compose Validation
      run: docker-compose config
      
    - name: Build Docker Images
      run: docker-compose build
      
    - name: Test Docker Compose Up
      run: |
        docker compose up -d
        sleep 30  # Aguarda 30 segundos para os serviços iniciarem
        docker-compose ps
        docker-compose logs
        docker-compose down
