name: CI PulseVault

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        
    - name: Run Django Tests
      env:
        DJANGO_SECRET_KEY: testing_key
        DEBUG: True
        ALLOWED_HOSTS: localhost,127.0.0.1
        DOCKER_MODE: False
      run: |
        python manage.py test
        
    - name: Run Flake8
      run: flake8 .

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        cp .env.ci .env
        cat .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker info
      run: |
        docker version
        docker info

    - name: Docker Compose Validation
      run: docker compose config
      
    - name: Build Docker Images
      run: docker compose build --no-cache
      
    - name: Test Docker Compose Up
      run: |
        docker compose up -d
        echo "Aguardando serviços iniciarem..."
        sleep 30
        echo "Verificando status dos containers..."
        docker compose ps
        echo "Verificando logs dos containers..."
        docker compose logs
        echo "Parando containers..."
        docker compose down
